apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
      - name: api-app
        image: endybits/fastapi-mysql-k8s:0.0.1
        ports:
        - containerPort: 80
        env:
        - name: HOST_DB
          value: mysql-service
        - name: PASSWORD_DB
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000